<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-23T18:37:20Z" name="Suite" finished-at="2023-02-23T18:37:29Z" duration-ms="8405">
    <groups>
    </groups>
    <test started-at="2023-02-23T18:37:20Z" name="Test" finished-at="2023-02-23T18:37:29Z" duration-ms="8405">
      <class name="com.lambdatest.TestNGTodo1">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.lambdatest.TestNGTodo1@37883b97]" started-at="2023-02-23T18:37:20Z" name="setup" finished-at="2023-02-23T18:37:23Z" duration-ms="2027" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.lambdatest.TestNGTodo1.basicTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@625732]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="basicTest()[pri:0, instance:com.lambdatest.TestNGTodo1@37883b97]" started-at="2023-02-23T18:37:23Z" name="basicTest" finished-at="2023-02-23T18:37:27Z" duration-ms="4336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.lambdatest.TestNGTodo1@37883b97]" started-at="2023-02-23T18:37:27Z" name="tearDown" finished-at="2023-02-23T18:37:27Z" duration-ms="248" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.lambdatest.TestNGTodo1@37883b97]" started-at="2023-02-23T18:37:27Z" name="setup" finished-at="2023-02-23T18:37:28Z" duration-ms="1382" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.lambdatest.TestNGTodo1.basicTest2()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@625732]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="basicTest2()[pri:0, instance:com.lambdatest.TestNGTodo1@37883b97]" started-at="2023-02-23T18:37:28Z" name="basicTest2" finished-at="2023-02-23T18:37:28Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Intentional failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Intentional failure
at org.testng.Assert.fail(Assert.java:96)
at com.lambdatest.TestNGTodo1.basicTest2(TestNGTodo1.java:92)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicTest2 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.lambdatest.TestNGTodo1@37883b97]" started-at="2023-02-23T18:37:28Z" name="tearDown" finished-at="2023-02-23T18:37:29Z" duration-ms="360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.lambdatest.TestNGTodo1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
